services:
  - type: web
    name: backend-sistema
    env: docker
    plan: free
    envVars:
      SPRING_DATASOURCE_URL: jdbc:mysql://hopper.proxy.rlwy.net:59556/railway
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: gtNmvjfPNBlwdJzUcKrdTSIerqvgaYfB
